name = "libpolymake_julia_jll"
uuid = "4d8266f6-2b3b-57e3-ad7a-d431eaaac945"
version = "0.1.0+0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
polymake_jll = "7c209550-9012-526c-9264-55ba7a78ba2c"

[compat]
julia = "1.0"
